// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: shellsage.proto

package api_client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PromptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptRequest) Reset() {
	*x = PromptRequest{}
	mi := &file_shellsage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptRequest) ProtoMessage() {}

func (x *PromptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shellsage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptRequest.ProtoReflect.Descriptor instead.
func (*PromptRequest) Descriptor() ([]byte, []int) {
	return file_shellsage_proto_rawDescGZIP(), []int{0}
}

func (x *PromptRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type SuggestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Suggestions   []string               `protobuf:"bytes,1,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestionResponse) Reset() {
	*x = SuggestionResponse{}
	mi := &file_shellsage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestionResponse) ProtoMessage() {}

func (x *SuggestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shellsage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestionResponse.ProtoReflect.Descriptor instead.
func (*SuggestionResponse) Descriptor() ([]byte, []int) {
	return file_shellsage_proto_rawDescGZIP(), []int{1}
}

func (x *SuggestionResponse) GetSuggestions() []string {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

var File_shellsage_proto protoreflect.FileDescriptor

const file_shellsage_proto_rawDesc = "" +
	"\n" +
	"\x0fshellsage.proto\x12\tshellsage\"'\n" +
	"\rPromptRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\"6\n" +
	"\x12SuggestionResponse\x12 \n" +
	"\vsuggestions\x18\x01 \x03(\tR\vsuggestions2_\n" +
	"\x10ShellSageService\x12K\n" +
	"\fAutocomplete\x12\x18.shellsage.PromptRequest\x1a\x1d.shellsage.SuggestionResponse(\x010\x01B!Z\x1fshellsage-client/api-client;apib\x06proto3"

var (
	file_shellsage_proto_rawDescOnce sync.Once
	file_shellsage_proto_rawDescData []byte
)

func file_shellsage_proto_rawDescGZIP() []byte {
	file_shellsage_proto_rawDescOnce.Do(func() {
		file_shellsage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shellsage_proto_rawDesc), len(file_shellsage_proto_rawDesc)))
	})
	return file_shellsage_proto_rawDescData
}

var file_shellsage_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_shellsage_proto_goTypes = []any{
	(*PromptRequest)(nil),      // 0: shellsage.PromptRequest
	(*SuggestionResponse)(nil), // 1: shellsage.SuggestionResponse
}
var file_shellsage_proto_depIdxs = []int32{
	0, // 0: shellsage.ShellSageService.Autocomplete:input_type -> shellsage.PromptRequest
	1, // 1: shellsage.ShellSageService.Autocomplete:output_type -> shellsage.SuggestionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shellsage_proto_init() }
func file_shellsage_proto_init() {
	if File_shellsage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shellsage_proto_rawDesc), len(file_shellsage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shellsage_proto_goTypes,
		DependencyIndexes: file_shellsage_proto_depIdxs,
		MessageInfos:      file_shellsage_proto_msgTypes,
	}.Build()
	File_shellsage_proto = out.File
	file_shellsage_proto_goTypes = nil
	file_shellsage_proto_depIdxs = nil
}
