// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: shellsage.proto

package api_client

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShellSageService_Autocomplete_FullMethodName = "/shellsage.ShellSageService/Autocomplete"
)

// ShellSageServiceClient is the client API for ShellSageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShellSageServiceClient interface {
	// Bi-directional streaming RPC
	Autocomplete(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PromptRequest, SuggestionResponse], error)
}

type shellSageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShellSageServiceClient(cc grpc.ClientConnInterface) ShellSageServiceClient {
	return &shellSageServiceClient{cc}
}

func (c *shellSageServiceClient) Autocomplete(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PromptRequest, SuggestionResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ShellSageService_ServiceDesc.Streams[0], ShellSageService_Autocomplete_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PromptRequest, SuggestionResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShellSageService_AutocompleteClient = grpc.BidiStreamingClient[PromptRequest, SuggestionResponse]

// ShellSageServiceServer is the server API for ShellSageService service.
// All implementations must embed UnimplementedShellSageServiceServer
// for forward compatibility.
type ShellSageServiceServer interface {
	// Bi-directional streaming RPC
	Autocomplete(grpc.BidiStreamingServer[PromptRequest, SuggestionResponse]) error
	mustEmbedUnimplementedShellSageServiceServer()
}

// UnimplementedShellSageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShellSageServiceServer struct{}

func (UnimplementedShellSageServiceServer) Autocomplete(grpc.BidiStreamingServer[PromptRequest, SuggestionResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Autocomplete not implemented")
}
func (UnimplementedShellSageServiceServer) mustEmbedUnimplementedShellSageServiceServer() {}
func (UnimplementedShellSageServiceServer) testEmbeddedByValue()                          {}

// UnsafeShellSageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShellSageServiceServer will
// result in compilation errors.
type UnsafeShellSageServiceServer interface {
	mustEmbedUnimplementedShellSageServiceServer()
}

func RegisterShellSageServiceServer(s grpc.ServiceRegistrar, srv ShellSageServiceServer) {
	// If the following call pancis, it indicates UnimplementedShellSageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShellSageService_ServiceDesc, srv)
}

func _ShellSageService_Autocomplete_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ShellSageServiceServer).Autocomplete(&grpc.GenericServerStream[PromptRequest, SuggestionResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShellSageService_AutocompleteServer = grpc.BidiStreamingServer[PromptRequest, SuggestionResponse]

// ShellSageService_ServiceDesc is the grpc.ServiceDesc for ShellSageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShellSageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shellsage.ShellSageService",
	HandlerType: (*ShellSageServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Autocomplete",
			Handler:       _ShellSageService_Autocomplete_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "shellsage.proto",
}
