# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: shellsage.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'shellsage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fshellsage.proto\x12\tshellsage\"\x1f\n\rPromptRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\")\n\x12SuggestionResponse\x12\x13\n\x0bsuggestions\x18\x01 \x03(\t2_\n\x10ShellSageService\x12K\n\x0c\x41utocomplete\x12\x18.shellsage.PromptRequest\x1a\x1d.shellsage.SuggestionResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shellsage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROMPTREQUEST']._serialized_start=30
  _globals['_PROMPTREQUEST']._serialized_end=61
  _globals['_SUGGESTIONRESPONSE']._serialized_start=63
  _globals['_SUGGESTIONRESPONSE']._serialized_end=104
  _globals['_SHELLSAGESERVICE']._serialized_start=106
  _globals['_SHELLSAGESERVICE']._serialized_end=201
# @@protoc_insertion_point(module_scope)
